# Java 异常
***
## Code
```java
package cn.nssas.eelantech.service;

import cn.nssas.eelantech.common.Constant;
import cn.nssas.eelantech.handlers.MicroSituationHandler;
import cn.nssas.eelantech.handlers.SafetyAttackHandler;
import cn.nssas.eelantech.models.ThreatStatistics;
import cn.nssas.eelantech.utils.Holder;
import cn.nssas.eelantech.utils.KafkaUtil;
import org.apache.kafka.clients.consumer.ConsumerRecord;
import org.apache.kafka.clients.consumer.ConsumerRecords;
import org.apache.kafka.clients.consumer.KafkaConsumer;
import org.apache.kafka.clients.producer.KafkaProducer;
import org.apache.kafka.clients.producer.ProducerRecord;
import org.apache.log4j.Logger;
import org.json.JSONObject;
import org.springframework.stereotype.Service;

import java.io.PrintWriter;
import java.io.StringWriter;
import java.util.*;

public class SafetyAttackService implements Runnable {

    @Override
    public void run() {
        while (true) {
                try {
                    ······
                }catch (Exception e) {
                    StringWriter sw = new StringWriter();
                    PrintWriter pw = new PrintWriter(sw, true);
                    e.printStackTrace(pw);
                    pw.flush();
                    sw.flush();
                    System.out.println(sw.toString());
                }
            }
        }
    }
}
```

## 参考链接
- [Java中获取Exception的详细信息](https://1017401036.iteye.com/blog/2383663)
